###GET - List products
GET http://localhost:8080/v1/products

###GET - Get a product by ID
GET http://localhost:8080/v1/products/1

###POST - Create a product
POST http://localhost:8080/v1/products

{
  "name": "Teste"
}

###PUT - Update a product
PUT http://localhost:8080/v1/products/1

{
  "name": "Teste",
  "description": "ABC"
}

###DELETE - Delete a product by ID
DELETE http://localhost:8080/v1/products/2